import os
from dotenv import load_dotenv
load_dotenv(verbose=True)
SALESFORCE_USERNAME = os.getenv("SALESFORCE_USERNAME")
SALESFORCE_PASSWORD = os.getenv("SALESFORCE_PASSWORD")
SALESFORCE_SECURITY_TOKEN = os.getenv("SALESFORCE_SECURITY_TOKEN")
SALESFORCE_IS_SANDBOX = os.getenv("SALESFORCE_IS_SANDBOX")
SALESFORCE_ORGANIZATION_ID = os.getenv("SALESFORCE_ORGANIZATION_ID")
DOMAIN = os.getenv("DOMAIN")
